### PR TITLE
fix leaderboard score formatting style

### LINKED ISSUE #3583: On all leaderboards, don't do "k" notation - show all the digits
### Context

c/o John Bash:

>There is a neck-and-neck race for first place, but it's unfortunate that exmateriae is now displaying at 10k at the Leaderboard. It makes it impossible for Lubos or Sergio to know how many points they're behind. Is there any good reason why it can't display as 10,008 or whatever?

Image

### Feature description

Go to five digits (or however many... but I think it's ~never more than five?) and add comma, so it looks more like:

Image

### PR DESCRIPTION
**Pull request by cemreinanc**
in the leaderboard component, replaced `abbreviatedNumber` formatter with a new formatter called `formatNumberBipm` for consistent and legible formatting.

changed class `font-mono` to `tabular-nums font-[425]` to match the optical font thickness with the previous monospaced design.

also added consistent decimal places formatting config for all of the column so it increases legibility.

fixes #3583

### CODE REVIEW

File: front_end/src/utils/formatters/number.ts [hunk 1]
```diff
@@ -120,3 +120,41 @@ export function formatNumberWithUnit(
...
+  );
+
+  // Build the final string
+  let result = formattedInteger;
+  if (decimals > 0 && fractionalPart) {
+    result += `.${fractionalPart}`;
+  }
+
+  return isNegative ? `-${result}` : result;
+}
```
Comment (hlbmtc) [inline front_end/src/utils/formatters/number.ts:138]: I think we can simplify this by using `Number.toLocaleString()` instead:

```typescript
export function formatNumberBipm(val: number, decimals = 2): string {
  return num
    .toLocaleString("en-US", {
      minimumFractionDigits: decimals,
      maximumFractionDigits: decimals,
    })
    .replace(/,/g, "\u202F");
}
```

Comment (cemreinanc) [reply front_end/src/utils/formatters/number.ts:138]: Yes, now I changed it and simplified similar to this, just instead of defining fixed decimals, changed argument to pass Intl.NumberFormatOptions object to make it more reusable in different places when needed.

Now any min/max decimals or significant digits configurable, or even currency and other units can be passed to use same BIPM notation.
