### PR TITLE
Fix multi-character sanitization

### LINKED ISSUE #4175: 12, 13, 14
https://github.com/Metaculus/metaculus/security/code-scanning/12
https://github.com/Metaculus/metaculus/security/code-scanning/13
https://github.com/Metaculus/metaculus/security/code-scanning/14

### PR DESCRIPTION
**Pull request by ncarazon**
Closes #4175 

This PR improves HTML sanitization for metadata descriptions.  
Added a shared `stripHtmlTags` helper and replaced ad‑hoc regex stripping in tournament/community/OG metadata.
- add `stripHtmlTags` utility that repeatedly removes tags until clean
- use `stripHtmlTags` in tournament, community, and OG metadata description parsing

## Summary by CodeRabbit

* **Refactor**
  * Consolidated HTML sanitization into a shared utility used across tournament metadata, community descriptions, and social sharing previews. Description previews now strip tags more reliably (including nested/malformed tags), resulting in cleaner, more consistent text shown in page summaries and link previews.

### CODE REVIEW

**Review by elisescu — APPROVED** [review]
LGTM

File: front_end/src/utils/formatters/string.ts [hunk 1]
```diff
@@ -17,3 +17,20 @@ export function getValidString(
...
+ * until no tags remain. This prevents incomplete multi-character sanitization
+ * vulnerabilities where nested or malformed tags could leave dangerous content.
+ */
+export function stripHtmlTags(html: string): string {
+  let previous = "";
+  let current = html;
+
+  while (previous !== current) {
+    previous = current;
+    current = current.replace(/<[^>]*>/g, "");
```
Comment (elisescu) [inline front_end/src/utils/formatters/string.ts:32]: Does this not fail with examples like: <div data="a > b"> ? Is that not a concern?

Comment (ncarazon) [reply front_end/src/utils/formatters/string.ts:32]: Good catch! You're right, that would leave ` b">` behind.

I think it's fine for this case though - we're just sanitizing descriptions for meta tags, and attributes with `>` in them should be pretty rare in our tournament/community content. The iterative approach still fixes the main issue with nested tags from #4175.

If this becomes a problem we can swap it for a proper HTML parser, but I think regex is good enough here.
