### PR TITLE
fix: share url handling

### LINKED ISSUE #3756: searching, then clicking question, then clicking share to x, creates URL with search as URL, not the question.
See here: 

Image

### PR DESCRIPTION
**Pull request by cemreinanc**
Fixes #3756

## Summary by CodeRabbit

* **Bug Fixes**
  * More accurate URL handling for copy-to-clipboard so copied links include current path, query parameters, and hash.
  * More reliable Twitter and Facebook sharing links by consistently constructing the full page URL.
  * Unified URL construction across sharing and copying features for improved consistency and reliability.

### CODE REVIEW

File: front_end/src/hooks/share.ts [hunk 1]
```diff
@@ -31,21 +37,31 @@ export const useMetaImageUrl = (tagName: string) => {
...
   return useMemo(() => {
-    if (typeof window !== "undefined") {
-      return `https://twitter.com/intent/tweet?text=${encodeURIComponent(
-        message
-      )}&url=${encodeURIComponent(window.location.href)}`;
+    if (typeof window === "undefined") {
+      return "";
     }
-  }, [message]);
+    const url = `${window.location.origin}${pathname}${searchParams.toString() ? `?${searchParams.toString()}` : ""}`;
```
Comment (ncarazon) [inline front_end/src/hooks/share.ts]: This URL construction is missing the hash fragment. The original `window.location.href` included the hash (e.g., `#comment-456`), but this new construction doesn't.

**Impact**: If a user views `/questions/123#comment-456` and shares, the hash is stripped. The codebase uses hash fragments for comment links (`#comment-${comment.id}`), so sharing links to specific comments would break.

**Suggested fix**:
```javascript
const url = `${window.location.origin}${pathname}${searchParams.toString() ? `?${searchParams.toString()}` : ""}${window.location.hash}`;
```

This same fix should be applied to `useCopyUrl` (line 9) and `useShareOnFacebookLink` (line 62) as well.

**Review by ncarazon — CHANGES_REQUESTED** [review]
The approach using Next.js navigation hooks is correct for fixing the stale URL issue. However, there's a regression with hash fragments - see inline comment.

**Review by ncarazon — APPROVED** [review]
lgmt
